// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGrrGpwfv7Cp1nnRTC7qQXZgXgYjJiwLc',
    appId: '1:478575784185:web:58ae798ae2950ae77d3228',
    messagingSenderId: '478575784185',
    projectId: 'savemomapps',
    authDomain: 'savemomapps.firebaseapp.com',
    databaseURL: 'https://savemomapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemomapps.firebasestorage.app',
    measurementId: 'G-X1JWE25VHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2TF3CMpKQa0tS8LgI6GdiTTcg0EPuFwQ',
    appId: '1:478575784185:android:0b824393681d31217d3228',
    messagingSenderId: '478575784185',
    projectId: 'savemomapps',
    databaseURL: 'https://savemomapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemomapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtLw7V1taKcyywQW8Gu-TjvGgPB112lo',
    appId: '1:478575784185:ios:ad95a7d5ea47d92a7d3228',
    messagingSenderId: '478575784185',
    projectId: 'savemomapps',
    databaseURL: 'https://savemomapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemomapps.firebasestorage.app',
    androidClientId: '478575784185-dlttp8g4h04t5171hmmc88rmvhr16lo5.apps.googleusercontent.com',
    iosClientId: '478575784185-altevf9lqpi68qgivvcqcrb5u0j8b7sb.apps.googleusercontent.com',
    iosBundleId: 'com.savemom.allomom',
  );
}
